trigger:
- main

pool:
  name: Self-Hosted

steps:

- task: replacetokens@3
  displayName: 'Replace Tokens'
  inputs:
    targetFiles: '**/GeneralErrorTests.cs'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    useLegacyPattern: false
    enableTelemetry: true

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/ZeroSSL.Net.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      dir $(Build.ArtifactStagingDirectory)